"""initial_schema

Revision ID: 53a33688872d
Revises: 
Create Date: 2026-05-30 09:33:08.157006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a33688872d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_family', sa.String(), nullable=False),
    sa.Column('base_image_id', sa.String(), nullable=True),
    sa.Column('coords_x', sa.Integer(), nullable=True),
    sa.Column('coords_y', sa.Integer(), nullable=True),
    sa.Column('inpaints', sa.JSON(), nullable=True),
    sa.Column('character_name', sa.String(), nullable=True),
    sa.Column('tile_type', sa.String(), nullable=True),
    sa.Column('structure_subtype', sa.String(), nullable=True),
    sa.Column('generation_mode', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_records_asset_family'), 'asset_records', ['asset_family'], unique=False)
    op.create_index(op.f('ix_asset_records_base_image_id'), 'asset_records', ['base_image_id'], unique=False)
    op.create_index(op.f('ix_asset_records_id'), 'asset_records', ['id'], unique=False)
    op.create_table('background_tile_records',
    sa.Column('background_tile_id', sa.String(), nullable=False),
    sa.Column('tile_type', sa.String(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['asset_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('background_tile_id')
    )
    op.create_index(op.f('ix_background_tile_records_tile_type'), 'background_tile_records', ['tile_type'], unique=False)
    op.create_table('leader_records',
    sa.Column('leader_id', sa.String(), nullable=False),
    sa.Column('leader_name', sa.String(), nullable=False),
    sa.Column('leader_description', sa.String(), nullable=False),
    sa.Column('archetype', sa.String(), nullable=False),
    sa.Column('culture', sa.String(), nullable=False),
    sa.Column('time_of_day', sa.String(), nullable=False),
    sa.Column('mood', sa.String(), nullable=False),
    sa.Column('splash_image_id', sa.String(), nullable=True),
    sa.Column('splash_seed', sa.Integer(), nullable=False),
    sa.Column('splash_prompt', sa.String(), nullable=False),
    sa.Column('profile_image_id', sa.String(), nullable=True),
    sa.Column('action_image_ids', sa.JSON(), nullable=True),
    sa.Column('reference_filename', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['profile_image_id'], ['asset_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['splash_image_id'], ['asset_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('leader_id')
    )
    op.create_index(op.f('ix_leader_records_leader_id'), 'leader_records', ['leader_id'], unique=False)
    op.create_index(op.f('ix_leader_records_splash_image_id'), 'leader_records', ['splash_image_id'], unique=False)
    op.create_table('object_records',
    sa.Column('object_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('biome', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('prompt_used', sa.String(), nullable=False),
    sa.Column('generation_mode', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['asset_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_index(op.f('ix_object_records_category'), 'object_records', ['category'], unique=False)
    op.create_index(op.f('ix_object_records_created_at'), 'object_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_object_records_image_id'), 'object_records', ['image_id'], unique=False)
    op.create_index(op.f('ix_object_records_object_id'), 'object_records', ['object_id'], unique=False)
    op.create_table('structure_records',
    sa.Column('structure_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('style', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('scale', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('prompt_used', sa.String(), nullable=False),
    sa.Column('generation_mode', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['asset_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('structure_id')
    )
    op.create_index(op.f('ix_structure_records_category'), 'structure_records', ['category'], unique=False)
    op.create_index(op.f('ix_structure_records_created_at'), 'structure_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_structure_records_image_id'), 'structure_records', ['image_id'], unique=False)
    op.create_index(op.f('ix_structure_records_structure_id'), 'structure_records', ['structure_id'], unique=False)
    op.create_table('terrain_records',
    sa.Column('terrain_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('scale', sa.String(), nullable=False),
    sa.Column('material', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('prompt_used', sa.String(), nullable=False),
    sa.Column('generation_mode', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['asset_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('terrain_id')
    )
    op.create_index(op.f('ix_terrain_records_category'), 'terrain_records', ['category'], unique=False)
    op.create_index(op.f('ix_terrain_records_created_at'), 'terrain_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_terrain_records_image_id'), 'terrain_records', ['image_id'], unique=False)
    op.create_index(op.f('ix_terrain_records_terrain_id'), 'terrain_records', ['terrain_id'], unique=False)
    op.create_table('unit_records',
    sa.Column('unit_id', sa.String(), nullable=False),
    sa.Column('unit_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('prompt_used', sa.String(), nullable=False),
    sa.Column('generation_mode', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['asset_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_index(op.f('ix_unit_records_created_at'), 'unit_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_unit_records_image_id'), 'unit_records', ['image_id'], unique=False)
    op.create_index(op.f('ix_unit_records_unit_id'), 'unit_records', ['unit_id'], unique=False)
    op.create_index(op.f('ix_unit_records_unit_type'), 'unit_records', ['unit_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_records_unit_type'), table_name='unit_records')
    op.drop_index(op.f('ix_unit_records_unit_id'), table_name='unit_records')
    op.drop_index(op.f('ix_unit_records_image_id'), table_name='unit_records')
    op.drop_index(op.f('ix_unit_records_created_at'), table_name='unit_records')
    op.drop_table('unit_records')
    op.drop_index(op.f('ix_terrain_records_terrain_id'), table_name='terrain_records')
    op.drop_index(op.f('ix_terrain_records_image_id'), table_name='terrain_records')
    op.drop_index(op.f('ix_terrain_records_created_at'), table_name='terrain_records')
    op.drop_index(op.f('ix_terrain_records_category'), table_name='terrain_records')
    op.drop_table('terrain_records')
    op.drop_index(op.f('ix_structure_records_structure_id'), table_name='structure_records')
    op.drop_index(op.f('ix_structure_records_image_id'), table_name='structure_records')
    op.drop_index(op.f('ix_structure_records_created_at'), table_name='structure_records')
    op.drop_index(op.f('ix_structure_records_category'), table_name='structure_records')
    op.drop_table('structure_records')
    op.drop_index(op.f('ix_object_records_object_id'), table_name='object_records')
    op.drop_index(op.f('ix_object_records_image_id'), table_name='object_records')
    op.drop_index(op.f('ix_object_records_created_at'), table_name='object_records')
    op.drop_index(op.f('ix_object_records_category'), table_name='object_records')
    op.drop_table('object_records')
    op.drop_index(op.f('ix_leader_records_splash_image_id'), table_name='leader_records')
    op.drop_index(op.f('ix_leader_records_leader_id'), table_name='leader_records')
    op.drop_table('leader_records')
    op.drop_index(op.f('ix_background_tile_records_tile_type'), table_name='background_tile_records')
    op.drop_table('background_tile_records')
    op.drop_index(op.f('ix_asset_records_id'), table_name='asset_records')
    op.drop_index(op.f('ix_asset_records_base_image_id'), table_name='asset_records')
    op.drop_index(op.f('ix_asset_records_asset_family'), table_name='asset_records')
    op.drop_table('asset_records')
    # ### end Alembic commands ###
